version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: sca-db
    restart: always
    environment:
      MYSQL_DATABASE: savings_collection
      MYSQL_ROOT_PASSWORD: Password133-
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sca-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=savings_collection
      - DB_USER=root
      - DB_PASSWORD=Password133-
    depends_on:
      - db

volumes:
  mysql_data:
